worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /nix/store/*/etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        root /app;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?path=$uri&$args;
        }

        location ~ \.php$ {
            fastcgi_pass unix:/run/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}